// This file is auto-generated by @hey-api/openapi-ts

export const $entity_Todo = {
    type: 'object',
    properties: {
        completed: {
            type: 'boolean'
        },
        created_at: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        },
        user_id: {
            type: 'string'
        }
    }
} as const;

export const $usecase_CreateTodoRequest = {
    required: ['description', 'title', 'user_id'],
    type: 'object',
    properties: {
        completed: {
            type: 'boolean'
        },
        description: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        user_id: {
            type: 'string'
        }
    }
} as const;

export const $usecase_CreateUserRequest = {
    required: ['auth0_id', 'email', 'name', 'role'],
    type: 'object',
    properties: {
        auth0_id: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        role: {
            type: 'string',
            enum: ['admin', 'user']
        }
    }
} as const;

export const $usecase_TodoResponse = {
    type: 'object',
    properties: {
        completed: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        }
    }
} as const;

export const $usecase_UpdateTodoRequest = {
    type: 'object',
    properties: {
        completed: {
            type: 'boolean'
        },
        description: {
            type: 'string'
        },
        title: {
            type: 'string'
        }
    }
} as const;

export const $usecase_UpdateUserRequest = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        role: {
            type: 'string'
        }
    }
} as const;

export const $usecase_UserResponse = {
    type: 'object',
    properties: {
        createdAt: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        }
    }
} as const;